# Mysql
# jdbc:mysql://<host>:<puerto>/<nombre_base_de_datos>.
 
# URL=jdbc:mysql://localhost:3306/practica-mvc
# USERNAME=root
# PASSWORD=admin
 
# Postgres
# postgresql://<usuario>:<contraseña>@<host>:<puerto>/<nombre_de_la_base_de_datos>
 
URL=jdbc:postgresql://ep-old-shadow-ag3zj0iv.c-2.eu-central-1.aws.neon.tech/neondb
USERNAME=neondb_owner
PASSWORD=npg_QMdESk4R8fex